project:
  type: website

website:
  title: "5200 Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: data.ipynb 
        text: Data Gathering 
      - href: data_cleaning.ipynb 
        text: Data Cleaning

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



