project:
  type: website

website:
  title: "5200 Project"
  navbar:
    left:
      - href: authors.qmd
        text: About Us
      - href: data.ipynb
        text: The Data
      - about.qmd
    background: "#e1ccb7" #nav bar colors

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    linkcolor: "#e1ccb7"



